services:
  instock-frontend:
    container_name: instock-frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - instock-network
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
    environment:
      - PORT=3000
      - REACT_APP_API_URL=http://instock-backend:5000
      - CHOKIDAR_USEPOLLING=true
networks:
  instock-network:
    external: true
