services:
  instock-frontend:
    container_name: instock-frontend-app
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    networks:
      - instock-network
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - CHOKIDAR_USEPOLLING=true
networks:
  instock-network:
    external: true
